# Generated by Django 4.2 on 2024-03-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_prodect_photo_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
