# Generated by Django 4.2 on 2024-03-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_user_email_user_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bascet',
            new_name='Basket',
        ),
    ]
