# Generated by Django 4.2 on 2024-03-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_bascet_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='user',
        ),
    ]
