# Generated by Django 4.2 on 2024-03-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_basket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
