# Generated by Django 4.2 on 2024-03-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_user_name_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='user',
        ),
    ]
