# Generated by Django 4.2 on 2024-03-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_basket_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='Bascet',
        ),
    ]
