# Generated by Django 4.2 on 2024-03-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_basket_bascet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bascet',
            new_name='Basket',
        ),
    ]
